### ISSUE TITLE
invalid signature error on deployment

### ISSUE THREAD

**Issue by bitcoiners** [liquidapps-io/deepfreeze#1]
this is on  eos mainnet dsp cluster
/dapp-cluster-k8s# zeus unbox deepfreeze
⚙️Unboxing: deepfreeze
Error: invalid signature: 0x4f44213c
    at /dapp-cluster-k8s/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by NatPDeveloper** [comment]
Closing this since we're handling this in vgrab.
